---
name: Lint

"on":
  push:
    paths:
      - ".github/workflows/lint.yml"
      - "**.py"
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - "**.py"

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          # ST4 uses 3.8 internally
          python-version: 3.8.16
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: Install flake8
        run: |
          python -m pip install -U pip
          pip install flake8
      - name: Run flake8
        run: flake8 -v .
